In [199]:
import numpy as np
import sys

# The Basics
1. numpy is way faster because it's a fixed type. Way less bites to point to. 
2. Numpy use contiguous Memory -> Memory is compressed and at the same place. (lists is a lot of pointers pointing to differents places where the informations a scattered around) Numpy array is one pointer to the start and all the info is following. 
3. Single Instruction Multiple Data (SIMD) vector unit ???? 
4. Utilise in a better way in the cache. 


In [200]:
a = np.array([1, 2, 3])
b = np.array([2,2,2], dtype='int16')
c = np.array([[2,3,4], [4,5,6]])
d = np.array([[2,3,4], [4,5,6], [6,7,8]])
a*b

array([2, 4, 6])

In [201]:
# Get Dimensions
c.ndim

2

In [202]:
#Get Shapes 
d.shape

(3, 3)

In [203]:
# Get Types 
a.dtype

dtype('int64')

In [204]:
#Change types 
b.dtype

dtype('int16')

In [205]:
#Get Size in bytes
b.itemsize

2

In [206]:
a.itemsize

8

In [207]:
# Get total size : a.size *a.itemsize OR a.nbytes

a.nbytes

24

# Accessing / Changing elements, rows, columns 


In [208]:
matrix = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Get a specific element => [row, column] ; 
matrix[1, 2]

10

In [209]:
# Get a specific row 
matrix[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [210]:
# Get a specific column 
matrix[:, 2]

array([ 3, 10])

In [211]:
# Get Fancy 
matrix[:, 1:6:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])