In [199]:
import numpy as np
import sys

# The Basics
1. numpy is way faster because it's a fixed type. Way less bites to point to. 
2. Numpy use contiguous Memory -> Memory is compressed and at the same place. (lists is a lot of pointers pointing to differents places where the informations a scattered around) Numpy array is one pointer to the start and all the info is following. 
3. Single Instruction Multiple Data (SIMD) vector unit ???? 
4. Utilise in a better way in the cache. 


In [200]:
a = np.array([1, 2, 3])
b = np.array([2,2,2], dtype='int16')
c = np.array([[2,3,4], [4,5,6]])
d = np.array([[2,3,4], [4,5,6], [6,7,8]])
a*b

array([2, 4, 6])

In [201]:
# Get Dimensions
c.ndim

2

In [202]:
#Get Shapes 
d.shape

(3, 3)

In [203]:
# Get Types 
a.dtype

dtype('int64')

In [204]:
#Change types 
b.dtype

dtype('int16')

In [205]:
#Get Size in bytes
b.itemsize

2

In [206]:
a.itemsize

8

In [207]:
# Get total size : a.size *a.itemsize OR a.nbytes

a.nbytes

24

# Accessing / Changing elements, rows, columns 


In [208]:
matrix = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Get a specific element => [row, column] ; 
matrix[1, 2]

10

In [209]:
# Get a specific row 
matrix[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [210]:
# Get a specific column 
matrix[:, 2]

array([ 3, 10])

In [211]:
# Get Fancy 
matrix[:, 1:6:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

# 3d examples 
Work Ooutside in to find element. 

In [212]:
threedarr = np.array([[[1,2],[3,4]],[[4,5], [6,7]]])
print(threedarr)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [215]:
threedarr[1,1, 1]

7

# Initialize differents types of arrays : 

In [223]:
# All Zeros matrix : argulment is shape. 
# np.zeros(5) = 1 dimension. 
zero = np.zeros((2, 2, 4, 5, 2))
print(zero)

[[[[[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]]]



 [[[[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]
    [0. 0.]]]]

In [225]:
# All ones matrix 
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [226]:
# Any number full => 
np.full((4,2,2), 5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [ ]:
# Any number full-like 
# Get the shape of a matrix 
np.full_like(matrix, number)

In [227]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.69302887, 0.91931487],
       [0.96500926, 0.17573813],
       [0.78078499, 0.01959024],
       [0.16553559, 0.30660659]])

In [228]:
# Random integer values
#Randint(max num or range, shape )
np.random.randint(7, size=(3,3))

array([[0, 5, 3],
       [5, 5, 3],
       [5, 6, 3]])

In [229]:
# Identity matrix
#pure RREF matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [231]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
r2 = np.repeat(arr, 4, axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [241]:
exercise = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
exercise[1:-1,1:-1 ] = z

print(exercise)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays !!!!!!
# Because every elements points to the same memory

In [244]:
# a=np.array([1,2,3])
b = a
b
b[0] = 100
print(a)

[100   2   3]


In [ ]:
# a=np.array([1,2,3])
b = a.copy


# Mathematics ! 
# Row operations and matrics / vectors operations are ok ! 

In [247]:
a=np.array([1,2,3])

In [248]:
a+2

array([3, 4, 5])

In [ ]:
a*2

In [ ]:
a/2

In [249]:
a**2

array([1, 4, 9])